# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_location_latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_location_longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.TextField(default='helsinki', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
